# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeruser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=4000)),
                ('user_dob', models.CharField(max_length=4000)),
                ('user_email', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField()),
                ('user_password', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'register_user',
            },
        ),
    ]
