# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezeadmin', '0003_auto_20180429_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadpdf',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_name', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'pdf_uploaded',
            },
        ),
    ]
